#!/bin/sh

# 安装后执行的脚本

chmod a+x /usr/share/SM18.05-WINE-Vessel/Wine-x86_64-ubuntu.latest.AppImage
ln -s /usr/share/SM18.05-WINE-Vessel/Wine-x86_64-ubuntu.latest.AppImage /usr/bin/sm-wine

# 获取桌面路径
# desk=`cat $HOME/.config/user-dirs.dirs | grep DESKTOP | tail  -1  |cut -d '=' -f 2  | sed 's/\"//g'`
# var=`eval echo $desk`
# echo "当前桌面路径：$var"


# 创建父目录
mkdir -p /usr/share/SM18.05-WINE-Vessel/drive_c/SuperMemo/SuperMemo资料库
mkdir -p /home/SuperMemo卡组与资料库/


# 添加C盘、D盘、E盘卡包文件夹与资料库，应放到明显的位置打开。
ln -s /usr/share/SM18.05-WINE-Vessel/drive_c/SuperMemo/systems /home/SuperMemo卡组与资料库/SuperMemo_C盘卡组
ln -s /usr/share/SM18.05-WINE-Vessel/drive_d/ /home/SuperMemo卡组与资料库/SuperMemo_D盘卡组
ln -s /usr/share/SM18.05-WINE-Vessel/drive_e/ /home/SuperMemo卡组与资料库/SuperMemo_E盘卡组
ln -s /usr/share/SM18.05-WINE-Vessel/drive_c/SuperMemo/SuperMemo资料库 /home/SuperMemo卡组与资料库/SuperMemo_C盘资料库
