#!/bin/sh

# 安装后执行的脚本

# chmod a+x /opt/apps/supermemo/SM18.05-WINE-Vessel/Wine-x86_64-ubuntu.latest.AppImage
# ln -s /opt/apps/supermemo/SM18.05-WINE-Vessel/Wine-x86_64-ubuntu.latest.AppImage /usr/bin/sm-wine

# 创建父目录
mkdir -p /opt/apps/supermemo/SM18.05-WINE-Vessel/drive_c/SuperMemo/SuperMemo资料库
mkdir -p "/home/"${LOGNAME}"/桌面/SuperMemo卡组与资料库/"
# 给予SuperMemo资料库所有用户读写权限
sudo chmod a+rw /opt/apps/supermemo/SM18.05-WINE-Vessel/drive_c/SuperMemo/SuperMemo资料库
sudo chmod a+rw "/home/"${LOGNAME}"/桌面/SuperMemo卡组与资料库/"

# 添加C盘、D盘、E盘卡包文件夹与资料库，应放到明显的位置打开。
ln -s /opt/apps/supermemo/SM18.05-WINE-Vessel/drive_c/SuperMemo/systems "/home/"${LOGNAME}"/桌面/SuperMemo卡组与资料库/SuperMemo_C盘卡组"
ln -s /opt/apps/supermemo/SM18.05-WINE-Vessel/drive_d/ "/home/"${LOGNAME}"/桌面/SuperMemo卡组与资料库/SuperMemo_D盘卡组"
ln -s /opt/apps/supermemo/SM18.05-WINE-Vessel/drive_e/ "/home/"${LOGNAME}"/桌面/SuperMemo卡组与资料库/SuperMemo_E盘卡组"
ln -s /opt/apps/supermemo/SM18.05-WINE-Vessel/drive_c/SuperMemo/SuperMemo资料库 "/home/"${LOGNAME}"/桌面/SuperMemo卡组与资料库/SuperMemo_C盘资料库"
